---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tecnocursos-fastapi
  namespace: tecnocursos-production
  labels:
    app: tecnocursos-fastapi
    component: backend
    environment: production
    version: v2.0.0
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: "TecnoCursos AI FastAPI Backend"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: tecnocursos-fastapi
      component: backend
  template:
    metadata:
      labels:
        app: tecnocursos-fastapi
        component: backend
        environment: production
        version: v2.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: tecnocursos-serviceaccount
      
      # Anti-affinity para distribuir pods
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tecnocursos-fastapi
              topologyKey: kubernetes.io/hostname
      
      containers:
      - name: fastapi
        image: ghcr.io/tecnocursos/tecnocursos-ai:latest
        imagePullPolicy: Always
        
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tecnocursos-secrets
              key: database-url
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tecnocursos-secrets
              key: secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tecnocursos-secrets
              key: openai-api-key
              optional: true
        - name: AZURE_SPEECH_KEY
          valueFrom:
            secretKeyRef:
              name: tecnocursos-secrets
              key: azure-speech-key
              optional: true
        - name: D_ID_API_KEY
          valueFrom:
            secretKeyRef:
              name: tecnocursos-secrets
              key: d-id-api-key
              optional: true
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: tecnocursos-secrets
              key: sentry-dsn
              optional: true
        
        # Resource limits e requests
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        
        # Startup probe para aplicações que demoram para iniciar
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        
        # Volume mounts
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: cache-volume
          mountPath: /app/cache
        - name: logs-volume
          mountPath: /app/logs
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      
      # Volumes
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir:
          sizeLimit: 1Gi
      - name: logs-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: config-volume
        configMap:
          name: tecnocursos-config
      
      # DNS Config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      
      # Image pull secrets
      imagePullSecrets:
      - name: github-registry-secret

---
# HorizontalPodAutoscaler para auto-scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tecnocursos-fastapi-hpa
  namespace: tecnocursos-production
  labels:
    app: tecnocursos-fastapi
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tecnocursos-fastapi
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60

---
# PodDisruptionBudget para alta disponibilidade
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tecnocursos-fastapi-pdb
  namespace: tecnocursos-production
  labels:
    app: tecnocursos-fastapi
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: tecnocursos-fastapi
      component: backend 